version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: hotel-postgres
    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hotel-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
